version: "2"
services:
  application:
    image: maven:3.5.0-jdk-8-alpine
    container_name: springboot_sonar
    working_dir: /usr/library/
    volumes:
    - ./:/usr/library
    command: sh -c "mvn sonar:sonar -Dsonar.host.url={{SONAR_HOST}} -Dsonar.login={{SONAR_TOKEN}}"